config/routes.rb
Rails.application.routes.draw do
  get 'quscores/changevote' => 'quscores#change_vote'
  get 'anscores/changevote' => 'anscores#change_vote'

  resources :anscores
  resources :quscores
  resources :tags
  devise_for :users
  resources :users
  resources :answers
  resources :questions
  root to: "questions#index"

end

app/models/quscore.rb
class Quscore < ActiveRecord::Base
  belongs_to :user
  belongs_to :question

end

app/controllers/quscores_controller.rb
class QuscoresController < ApplicationController
  def change_vote
    if current_user.nil?
      render json: { result: "Please login first" , status: "2" }
    else
      question_id = params[:question_id]
      vote = params[:vote] == "up"?  1 : -1

      qs = QuestionScoreService.new({question_id: question_id, vote: vote, user_id: current_user.id})
      result = qs.update()

      render json: { result: result , status: "1" }
    end
  end
end

app/helpers/quscores_helper.rb
module QuscoresHelper
end

app/views/quscores/_form.html.erb
<%= form_for(@quscore) do |f| %>
  <% if @quscore.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quscore.errors.count, "error") %> prohibited this quscore from being saved:</h2>

      <ul>
      <% @quscore.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quscores/edit.html.erb
<h1>Editing quscore</h1>

<%= render 'form' %>

<%= link_to 'Show', @quscore %> |
<%= link_to 'Back', quscores_path %>

app/views/quscores/index.html.erb
<h1>Listing quscores</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quscores.each do |quscore| %>
      <tr>
        <td><%= link_to 'Show', quscore %></td>
        <td><%= link_to 'Edit', edit_quscore_path(quscore) %></td>
        <td><%= link_to 'Destroy', quscore, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quscore', new_quscore_path %>

app/views/quscores/new.html.erb
<h1>New quscore</h1>

<%= render 'form' %>

<%= link_to 'Back', quscores_path %>

app/views/quscores/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_quscore_path(@quscore) %> |
<%= link_to 'Back', quscores_path %>