config/routes.rb
Rails.application.routes.draw do
  get 'quscores/changevote' => 'quscores#change_vote'
  get 'anscores/changevote' => 'anscores#change_vote'

  resources :anscores
  resources :quscores
  resources :tags
  devise_for :users
  resources :users
  resources :answers
  resources :questions
  root to: "questions#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
 <head>
    <meta charset="utf-8">
    <title>QA Pets</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>

    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
 </head>
    <body>
      <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div clas="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
            data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to "QAPets", root_url, class: "navbar-brand" %>
            <%= link_to "Users", users_path, class: "navbar-brand" %>
            <%= link_to "Ask A Question", new_question_path, class: "navbar-brand" %>
          </div>
          <div class="navbar-collapse collapse">

      <% if user_signed_in? %>

      <div class="navbar-form navbar-right">
        <p class="navbar-text">
          Signed in as: <%= image_tag avatar_nav(current_user) %>
          <%= link_to "#{current_user.email}", current_user %>
        </p>
        <p class="navbar-text">
          Not You? <%= link_to 'Sign Out',
          destroy_user_session_path, :method => :delete %>
        </p>
      </div>

        <% else %>

          <div class="navbar-form navbar-right">
            <%= form_for(:user, :url => session_path(:user)) do |f| %>
            <div class="form-group">
              <%= f.email_field :email, placeholder: "Email", class: "form-control" %>
            </div>
            <div class="form-group">
              <%= f.password_field :password, placeholder: "Password", class: "form-control" %>
            </div>
            <div class="form-group">
            <%= f.submit 'Sign In', class: "btn btn-success" %>
            </div>
            <div class="form-group">
              <%= link_to 'Sign Up!', new_user_registration_path %>
            </div>
            <div class="form-group">
              <%= link_to "Forgot your password?", new_password_path(:user), class: "navbar-link" %>
            </div>
          </div>

          <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <%= yield %>

  </div>

    </div>
  </body>
</html>